meta_product_name: "BidnBill"
meta_title: "BidnBill - Take control of your bills"
meta_description: "Create bids on your day-to-day bills to pitch out competitors"
meta_image: "icon-bidnbill.png"
twitter_account: "@BidnBill"
